name: Deploy Web Demo 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Disable Incremental Build
      run: echo "CARGO_INCREMENTAL=0" >> "$GITHUB_ENV"

    - uses: actions/checkout@v3

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build WASM
      working-directory: web-demo/datalog_wasm 
      run: wasm-pack build --target web 

    # Upload the built website as an artifact, so that runs which are not deployed
    # (i.e. other branches and PRs) to Github Pages can be be downloaded
    # (https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts)
    # and viewed locally.
    #
    # When Github adds support for PR Github Pages previews
    # (https://github.com/orgs/community/discussions/7730)
    # this can be removed.
    - name: Upload web artifact
      uses: actions/upload-artifact@v3
      with:
        name: www
        path: target/www

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # only actually deploy if pushed to main branch
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: web-demo/dist
        force_orphan: true